source "https://rubygems.org"

ruby "3.0.3"

abort "Bundler version >= 2.1.4 is required" if Gem::Version.new(Bundler::VERSION) < Gem::Version.new("2.1.4")

gem "activerecord"
gem "activesupport"
gem "allure-rspec"
gem "appium_capybara"
gem "appium_lib"
gem "byebug"
gem "capybara"
gem "capybara-screenshot"
gem "climate_control"
gem "combine_pdf"
gem "csv"
gem "dotenv"
gem "factory_bot", "~> 6.2.1"
gem "faker"
gem "faraday"
gem "faraday-typhoeus"
gem "http"
gem "mailosaur"
gem "monetize"
gem "open-uri"
gem "parallel_tests", "~> 3.7", ">= 3.7.1"
gem "pdf_matcher"
gem "pdf-reader"
gem "pg"
gem "pry"
gem "rest-client"
gem "retryable"
gem "rspec"
gem "rspec-retry"
gem "rspec_junit_formatter"
gem "selenium-webdriver"
gem "simplecov"
gem "site_prism"
gem "spring-commands-rspec"
gem "spring-watcher-listen"
gem "standard", group: [:development, :test]
gem "timecop"
gem "vcr"
gem "webmock"
gem "websocket-driver"
gem "yaml"

gem "identikal", "~> 0.1.2"
